[workspace]
members = ["app"]

[workspace.package]
authors = ["shengj.sang <shengj.sang@icloud.com>"]
edition = "2021"
license = "MIT"
publish = false
repository = ""


[workspace.dependencies]
axum = "0"
serde = "1"
serde_json = "1"
tokio = "1"
