[server]
name = "Axum-Admin"
# 服务器IP:端口
address = "0.0.0.0:8888"

[log]
dir = "logs"
prefix = "log"
# 日志级别  TRACE DEBUG  INFO  WARN ERROR
log_level = "DEBUG"

[database]
url = "postgres://postgres:123456@localhost/ava"

[redis]
url = "redis://localhost"


[captcha]
length = 6
noise = 0.5
width = 220
height = 80
